services:
  - type: web
    name: bitegit-sites-yellow
    env: node
    plan: starter
    branch: main
    buildCommand: npm install
    startCommand: node server.js
    healthCheckPath: /healthz
    maxShutdownDelaySeconds: 30
    numInstances: 2
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: ALLOW_DEMO_OTP
        value: true
      - key: ADMIN_USERNAME
        sync: false
      - key: ADMIN_PASSWORD
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: MASTER_ENCRYPTION_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DB_NAME
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: bitegit-shared-kv
          property: connectionString
  - type: worker
    name: bitegit-email-worker
    env: node
    plan: starter
    branch: main
    repo: https://github.com/Urmilanegi/bitegit-sites-yellow
    buildCommand: npm install
    startCommand: node worker.js
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: ADMIN_EMAIL
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: MAIL_FROM
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: REDIS_URL
        fromService:
          type: keyvalue
          name: bitegit-shared-kv
          property: connectionString
  - type: keyvalue
    name: bitegit-shared-kv
    plan: starter
    region: oregon
    ipAllowList: []
